### PR TITLE
fix error which came when trying to build docker image

### PR DESCRIPTION
**Pull request by gibkigonzo**
### Related issues

closes #

### Short description and why it's useful

2.
```
Creating sfa_redis_1 ... 
Creating elasticsearch ... error

Creating sfa_redis_1   ... done
62110". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for es7  Cannot create container for service es7: Conflict. The container name "/elasticsearch" is already in use by container "ca3203b26531bf209785f666688f36bf7d81fac97b54b1abc01d668738762110". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
```
That is probably because I have already container with same name (vsf-api), so I've added/changed names for containers to be uniq for this docker-compose.

3.
```
app_1    | Something went wrong installing the "sharp" module
app_1    | 
app_1    | Error loading shared library libvips-cpp.so.42: No such file or directory (needed by /var/www/node_modules/sharp/build/Release/sharp.node)
app_1    | 
app_1    | - Remove the "node_modules/sharp" directory, run "npm install" and look for errors
app_1    | - Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
app_1    | - Search for this error at https://github.com/lovell/sharp/issues
app_1    | 
app_1    | [nodemon] app crashed - waiting for file changes before starting...

```
needed to remove `vips-dev \` from Dockerfile because it makes partial install and sharp fails https://github.com/lovell/sharp/issues/773

### Screenshots of visual changes before/after (if there are any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with a description of your change

### Contribution and currently important rules acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/storefront-api/blob/develop/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ResuBaka** [comment]
Here you should wait for the PR #62 as with that we get that change too, with the version number.

**Comment by gibkigonzo** [comment]
Ok, I see that :) Then I will pull develop after https://github.com/DivanteLtd/storefront-api/pull/62/files

**Comment by ResuBaka** [comment]
The merge request #62 is merged. So you can update your branch.

**Comment by gibkigonzo** [comment]
@ResuBaka done

**Pull request merged**
