### PR TITLE
moved all modules to its own package

### PR DESCRIPTION
**Pull request by ResuBaka**
This is not tested at all as I have currently now working VSF instance or ES instance to test it.
It does start and he loads all modules and that all logic still works like it should I can#t
guarantee that it works like it should that needs to be tested.

### Screenshots of visual changes before/after (if there are any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with a description of your change

### Contribution and currently important rules acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/storefront-api/blob/develop/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ResuBaka** [comment]
I think I need to close this PR and open an other one as the CI does not run :disappointed: and I don't under stand why. 

But before that I write the support and maybe they have some info why the CI does not run.

**Comment by ResuBaka** [comment]
The ingratiation test are working good. 

I only need to change elasticsearch and redis/redis-tag-cache to be singletons. That is needed so I can close the connections after the tests are finished so that the test now they are finished.

**Comment by ResuBaka** [comment]
@pkarw  Do you know if there is some list or if some one from QA from the vue-storefront team create a list with query's that needs to be tested I they work? 

Other wise should we test the API endpoints for magento integrations? 
When yes I need to know if we just want to test magento2 and that against the demo shop from the vsf demo or if we want to create a demo docker image of magento2 and test against that one?

**Comment by pkarw** [comment]
Hi Jens! Sorry that I couldn't have started testing it by myself last week - I really want to start this week. Regarding the test scenarios we must test two cases:

a) VSF standard demo - including all operations lik cart sync, my account, catalog - via REST API
b) VSF standard demo - including all operations lik cart sync, my account, catalog - via GraphQL API - and I know there will be some discrepancies as I've changed the graphql format a llitttle bit :)

We can test it all on the default demo-magento2.vuestorefront.io credentials that are already included in the config - it's not a problem

**Pull request merged**
